// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBerQ9WXhYCX_vROn4p3org0IuIKAEj7Oo',
    appId: '1:984270542264:web:0614f99a7a433bda062b4d',
    messagingSenderId: '984270542264',
    projectId: 'final-disapp',
    authDomain: 'final-disapp.firebaseapp.com',
    storageBucket: 'final-disapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAPdJ9RHohDugxTxXq-m-UpHsa9HoUYd4',
    appId: '1:984270542264:android:8615c5a7f4347d8d062b4d',
    messagingSenderId: '984270542264',
    projectId: 'final-disapp',
    storageBucket: 'final-disapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDThw4WJPEgWOoQcGK6uI7DFpO2E6omPDI',
    appId: '1:984270542264:ios:63896389ef6f6476062b4d',
    messagingSenderId: '984270542264',
    projectId: 'final-disapp',
    storageBucket: 'final-disapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDThw4WJPEgWOoQcGK6uI7DFpO2E6omPDI',
    appId: '1:984270542264:ios:63896389ef6f6476062b4d',
    messagingSenderId: '984270542264',
    projectId: 'final-disapp',
    storageBucket: 'final-disapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBerQ9WXhYCX_vROn4p3org0IuIKAEj7Oo',
    appId: '1:984270542264:web:63cc7aeaaf3639f3062b4d',
    messagingSenderId: '984270542264',
    projectId: 'final-disapp',
    authDomain: 'final-disapp.firebaseapp.com',
    storageBucket: 'final-disapp.firebasestorage.app',
  );
}
